export const Menuitems = [
  {
    tag: "Dashboard",
    title: "Dashboard",
    icon: "ri-home-line",
    location: "dashboard",
  },
  {
    tag: "ClientManagement",
    title: "Client Management",
    icon: "ri-group-line",
    location: "clients",
  },
  {
    tag: "CenterManagement",
    title: "Center Management",
    icon: "ri-store-3-fill",
    location: "centers",
  },
  {
    tag: "SubscriptionManagement",
    title: "Subscription Management",
    icon: "ri-vip-crown-line",
    location: "subscriptions",
  },
  {
    tag: "ScaleManagement",
    title: "Scale Creation",
    icon: "ri-scan-line",
    location: "scales",
  },
  {
    tag: "AssessmentManagement",
    title: "Assessment Creation",
    icon: "ri-questionnaire-line",
    location: "assessments",
  },
  {
    tag: "SkillManagement",
    title: "Skill Management",
    icon: "ri-file-text-line",
    location: "skills",
  },
  {
    tag: "ContentManagement",
    title: "Content Management",
    icon: "ri-tv-2-line",
    location: "contents",
  },
  {
    tag: "DepartmentManagement",
    title: "Departments",
    icon: "ri-group-2-line",
    location: "departments",
  },
  {
    tag: "PatientManagement",
    title: "Patients",
    icon: "ri-user-4-line",
    location: "patients",
  },
  {
    tag: "AppointmentsManagement",
    title: "Appointments",
    icon: "ri-user-3-line",
    location: "appointments",
  },
  {
    tag: "TherapistManagement",
    title: "Therapist",
    icon: "ri-hand-heart-line",
    location: "therapist",
  },
  {
    tag: "TherapyMethodManagement",
    title: "Therapy Method",
    icon: "ri-body-scan-line",
    location: "therapies",
  },
  {
    tag: "PaymentReports",
    title: "Payment Reports",
    icon: "ri-bank-card-line",
    location: "payment-reports",
  },
  {
    tag: "ATStore",
    title: "AT Store",
    icon: "ri-store-line",
    location: "at-store",
  },
  {
    tag: "StoreInquiries",
    title: "Store Enquiries",
    icon: "ri-shield-user-line",
    location: "store-enquiries",
  },
  {
    tag: "Resources",
    title: "Free Resources",
    icon: "dripicons-document",
    location: "free-resource",
  },
];
